---
# k8s/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
images:
  - name: ghcr.io/thecodecloud007/spring-boot-k8s-demo
    newName: ghcr.io/thecodecloud007/spring-boot-k8s-demo
    newTag: sha-225f3b8