# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  K8S_DIR: k8s

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: ./mvnw clean package

      - name: Run tests
        run: ./mvnw test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=short
            type=ref,event=branch
            latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Kubernetes manifests
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Extract the image tag (short SHA)
          IMAGE_TAG=$(echo ${{ steps.meta.outputs.tags }} | grep -o "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-[a-f0-9]*" | head -1 | cut -d':' -f2)
          
          # Update the image tag in the kustomization.yaml file
          sed -i "s|newTag:.*|newTag: $IMAGE_TAG|" ${{ env.K8S_DIR }}/kustomization.yaml
          
          # Configure Git
          git config --global credential.username "thecodecloud007"
          git config --global user.email "thecodecloud.in@gmail.com"
          
          # Commit and push changes
          git add ${{ env.K8S_DIR }}/kustomization.yaml
          git commit -m "Update image tag to $IMAGE_TAG"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}